lib/sunstone_web/router.ex
defmodule SunstoneWeb.Router do
  use SunstoneWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SunstoneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  pipeline :auth do
    plug Sunstone.Accounts.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated, error_handler: SunstoneWeb.UserController
  end


  scope "/", SunstoneWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :landing
    get "/register", UserController, :register
    get "/login", UserController, :login
    post "/login", UserController, :create_login
    post "/new", UserController, :create
    post "/logout", UserController, :logout
    get "/contact", PageController, :contact
    get "/request_reset", UserController, :new_reset
    post "/request_reset", UserController, :create_reset
    get "/reset", UserController, :new_reset_password
    post "/reset", UserController, :create_reset_password
    put "/reset", UserController, :create_reset_password
  end


  scope "/", SunstoneWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    get "/office/new", OfficeController, :new
    post "/office/new", OfficeController, :create
    get "/office/invite/:hash_id", InviteController, :new
    post "/office/invite/:hash_id", InviteController, :create
    post "/office/accept/:hash_id", InviteController, :accept
    get "/office/uninvited/:hash_id", OfficeController, :uninvited
    live "/office/:hash_id", PageLive, :index
    get "/office", OfficeController, :index
  
  end

    scope "/", SunstoneWeb do
    pipe_through [:api, :auth, :ensure_auth]
    post "/office/:hash_id/notification", NotificationController, :new
  
  end


  # Other scopes may use custom stacks.
  # scope "/api", SunstoneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SunstoneWeb.Telemetry
    end
  end
end

lib/sunstone/chats/office.ex
defmodule Sunstone.Chats.Office do
  use Ecto.Schema
  import Ecto.Changeset
  alias Sunstone.Accounts.User
  alias Sunstone.Chats.Table
  alias Sunstone.Chats.Invite
  schema "offices" do
    field :name, :string
    belongs_to :owner, User, foreign_key: :owner_id
    has_many :tables, Table
    has_many :invites, Invite
    has_many :active_users, User, foreign_key: :active_office_id
    many_to_many(
      :users,
      User,
      join_through: "user_office",
      on_replace: :delete
    )
    timestamps()
  end

  @doc false
  def changeset(office, attrs, user) do
    users = [user]
    office
    |> cast(attrs, [:name])
    |> put_assoc(:owner, user)
    |> validate_required([:name, :owner])
    |> put_assoc(:users, users)
  end

  def add_user_changeset(office, user) do
    users = [user | office.users]
    office
    |> change(users: users)
  end
  
end

lib/sunstone_web/controllers/office_controller.ex
defmodule SunstoneWeb.OfficeController do
  use SunstoneWeb, :controller
  alias Sunstone.Chats
  alias Sunstone.Chats.Office
  alias Sunstone.Chats.Invite

  def index(conn, _) do
    user = Guardian.Plug.current_resource(conn)
    invites = Chats.list_invites_from_email(user.email)
    changeset = Office.changeset(%Office{}, %{}, user)
    render conn, "index.html", changeset: changeset, user: user, invites: invites
  end
  def new(conn, _params)  do
    user = Guardian.Plug.current_resource(conn)
    changeset = Office.changeset(%Office{}, %{}, user)
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"office" => office_params})  do
    user = Guardian.Plug.current_resource(conn)
    Chats.create_office(office_params, user)
    redirect(conn, to: Routes.office_path(conn, :index))
  end

  def invite(conn, %{"hash_id" => hash_id})  do
    changeset = Invite.changeset(%Invite{}, %{})

    render conn, "invite.html", changeset: changeset
  end

  def uninvited(conn, %{"hash_id" => hash_id})  do
    office_id = SunstoneWeb.UserController.decode_id(hash_id)
    office = Chats.get_office!(office_id)
    render conn, "uninvited.html", office: office
  end



end

lib/sunstone_web/views/office_view.ex
defmodule SunstoneWeb.OfficeView do
  use SunstoneWeb, :view
  

end

lib/sunstone_web/templates/office/index.html.eex
<div class="center-width">
<h1 style=" color: #606c76;margin:0;">Offices</h1>
<h6 style="color: #606c76;margin:0;"><%= @user.name %> | <%= @user.email %></h6>
<div style="margin-top:20px;">
  <%= link("Create Office", to: Routes.office_path(@conn, :new), class: "button") %> 
</div>
<div style="margin-top: 20px;">
  <%= for office <- @user.offices do %>
    <div  style="margin-top: 10px; margin-bottom: 10px; padding: 5px; border-radius: 5px;    box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24); transition: all 0.3s cubic-bezier(.25,.8,.25,1);">
                    <div class="row">
                        <div class="column">
                            <ul style="list-style: none; margin:0; list-style-type:none;white-space:nowrap;overflow-x:auto;">
                              <li style="font-size:20px; display: inline-grid; border-radius:5px;  float:left; height:100%; margin:0; padding-left:10px; padding-right:10px; padding-top:5px; margin-right:10px;">
                               <%=  office.name  %>
                              </li>
                            </ul>
                              <a href="<%= Routes.page_path(@conn, :index, SunstoneWeb.UserController.encode_id(office.id)) %>" style="margin-bottom:0; min-width: 102.743px; float:right;" class="button">Enter</a>
                                  <%= if @user.id === office.owner_id do %>
                                      <%= link("Invite Members", to: Routes.invite_path(@conn, :new, SunstoneWeb.UserController.encode_id(office.id)), class: "button button-outline", style: "float:right; margin-right: 10px;") %> 
                                  <% end %>

                        </div>
                    </div>
                </div>
    <% end %>
      <%= if length(@user.offices) == 0 do %>
        <div style = "color: #606c76">
          <h3 style="margin-bottom: 5px;">Its a bit lonely in here :(</h3>
          <h3>Create your own office or ask your colleague to invite you into their office.</h3>
        </div>
      <% end %>
</div>
<%= if length(@invites) > 0 do %>
  <h2 style="margin-top: 50px;">Invitations</h2>
    <%= for invite <- @invites do %>
      <%= form_for @changeset, Routes.invite_path(@conn, :accept, SunstoneWeb.UserController.encode_id(invite.office.id)), fn f -> %>
      <div style="margin-top: 10px; margin-bottom: 10px;">
                      <div class="row">
                              <ul style="list-style: none; margin:0; height:100%;list-style-type:none;white-space:nowrap;overflow-x:auto; width: 100%; padding: 5px;">
                                <li style="font-size:20px; display: inline-grid; border-radius:5px;  float:left; height:100%; margin:0; padding-left:10px; padding-right:10px; padding-top:5px; margin-right:10px;">
                                 <%=  invite.office.owner.name  %> has invited you to join <%=  invite.office.name  %>
                                </li>
                                 <%= submit "Accept", style: "margin-bottom:0; min-width: 102.743px; float:right;", class: "button"%>
                              </ul>
                        </div>
                  </div>
        <% end %>
    <% end %>
  <% end %>
</div>

lib/sunstone_web/templates/office/new.html.eex
<a href="/office" class = "button button-outline" style="margin-top: 20px;">Go Back</a>

<div class="center-width">
<%= form_for @changeset, Routes.office_path(@conn, :create), fn f -> %>
<div style="color:#606c76;">
    <label>
    Your office name : <%= text_input f, :name, placeholder: "Google" %>
    <%= error_tag f, :name %>
  </label>
</div>

  <%= submit "Create" %>
<% end %>
</div>

lib/sunstone_web/templates/office/uninvited.html.eex
<div class="center-width">
<h3 style="color: #606c76;">Unfortunately you are not invited to <span style="font-weight:bold"> <%= @office.name %> </span>.</h3>
<h3 style="color: #606c76;">Please ask the owner of the Office to invite you.</h3>
</div>