lib/sunstone_web/router.ex
defmodule SunstoneWeb.Router do
  use SunstoneWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SunstoneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  pipeline :auth do
    plug Sunstone.Accounts.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated, error_handler: SunstoneWeb.UserController
  end


  scope "/", SunstoneWeb do
    pipe_through [:browser, :auth]
    get "/", PageController, :landing
    get "/register", UserController, :register
    get "/login", UserController, :login
    post "/login", UserController, :create_login
    post "/new", UserController, :create
    post "/logout", UserController, :logout
    get "/contact", PageController, :contact
    get "/request_reset", UserController, :new_reset
    post "/request_reset", UserController, :create_reset
    get "/reset", UserController, :new_reset_password
    post "/reset", UserController, :create_reset_password
    put "/reset", UserController, :create_reset_password
  end


  scope "/", SunstoneWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    get "/office/new", OfficeController, :new
    post "/office/new", OfficeController, :create
    get "/office/invite/:hash_id", InviteController, :new
    post "/office/invite/:hash_id", InviteController, :create
    post "/office/accept/:hash_id", InviteController, :accept
    get "/office/uninvited/:hash_id", OfficeController, :uninvited
    live "/office/:hash_id", PageLive, :index
    get "/office", OfficeController, :index
  
  end

    scope "/", SunstoneWeb do
    pipe_through [:api, :auth, :ensure_auth]
    post "/office/:hash_id/notification", NotificationController, :new
  
  end


  # Other scopes may use custom stacks.
  # scope "/api", SunstoneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SunstoneWeb.Telemetry
    end
  end
end

lib/sunstone_web/views/layout_view.ex
defmodule SunstoneWeb.LayoutView do
  use SunstoneWeb, :view
end

lib/sunstone_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <div style="min-height:70vh;">
    <%= @inner_content %>
  </div>
  <h6 style="margin-top:40px;">Found any bugs or feature request? <a style="font-weight:bold" href = "mailto:hazmi@inoffice.chat">Contact Us</a></h6>
</main>

lib/sunstone_web/templates/layout/live.html.leex
<main role="main" class="container test">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/sunstone_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Inoffice", suffix: " · Your Virtual Office" %>
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://unpkg.com/peerjs@1.3.1/dist/peerjs.min.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-115169227-8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-115169227-8');
    </script>


  </head>
  <body style="margin: 0">
    <header  style="background-color:#F03A47; margin-bottom: 0;">
      <section class="container">
        <nav role="navigation">
        <style>
          #header-list > li {
            float: left;
          }
          #logo{
            color: white;
            font-weight: bold;
            font-size: 3rem;
          }
          form {
            margin-bottom: 0;
          }
          @media (min-width: 40.0rem) { /* Small devices (landscape phones, 576px and up) */
            #logo{
              margin-left:0;
            }
          }
        </style>
        <script>
          function loginRedirect() {
            location.href = "/login";
          }
          function contactRedirect() {
            location.href = "/contact";
          }
          function homeClick() {
            location.href = "/office";
          }
        </script>
          <ul id="header-list" >
            
            <%= if Guardian.Plug.current_resource(@conn) do %>
              <li>
              <button type="button" class= "button button-clear" onclick= "homeClick()"  style="color: white;">Home</button> 
              </li>
            <% end %>
             <li>
            <%= if Guardian.Plug.current_resource(@conn) do %>
              <%= form_for @conn, Routes.user_path(@conn, :logout), fn f -> %>
                <%= button("Logout", to: Routes.user_path(@conn, :logout), class: "button button-clear", type: "submit",  style: "color: white;")%> 
              <%= end %>
            <% else %>
              <button type="button" class= "button button-clear" onclick= "loginRedirect()" style="color: white;" >Login</button> 
            <% end %>
            </li>
          </ul>
        </nav>
        <a href="/" id="logo" >
          Inoffice
        </a>
      </section>
    </header>
    <div style="margin: 0;">
    <%= @inner_content %>
    </div>

  </body>
</html>